#PROCEDURAL_STARS will be present in next update

screen = [LIGHTING] [POST_PROCESS]

option.BLOOM_THRESHOLD=0.0 2.0
option.BLOOM_STRENGTH=0.0 3.0
option.BLOOM_RADIUS=0.0 10.0
option.GRAIN_STRENGTH=0.0 1.0


option.BLOOM=true false
option.DITHERING=true false
option.HALF_LAMBERT=true false
option.CLOUD_SHADOWS=true false
option.PROCEDURAL_STARS=true false


option.WAVETYPE=0 1

sliders = BLOOM_THRESHOLD BLOOM_STRENGTH BLOOM_RADIUS GRAIN_STRENGTH

screen.LIGHTING = [TERRAIN] [SKY] [WATER]

screen.TERRAIN = HALF_LAMBERT CLOUD_SHADOWS
screen.SKY = PROCEDURAL_STARS
screen.WATER=WAVETYPE
value.WAVETYPE.0=Simple
value.WAVETYPE.1=Detailed


screen.POST_PROCESS = [BLOOMS] [TEXTURES]

screen.BLOOMS = BLOOM BLOOM_THRESHOLD BLOOM_STRENGTH BLOOM_RADIUS
screen.TEXTURES = [GRAIN] DITHERING
screen.GRAIN = GRAIN_STRENGTH