# ===== ROOT =====
screen = [LIGHTING] [POST_PROCESS]

# ===== OPTIONS =====

# Sliders
option.BLOOM_THRESHOLD=0.0 2.0
option.BLOOM_STRENGTH=0.0 3.0
option.BLOOM_RADIUS=0.0 10.0
option.GRAIN_STRENGTH=0.0 1.0

# Toggles
option.BLOOM=true false
option.DITHERING=true false
option.HALF_LAMBERT=true false
option.CLOUD_SHADOWS=true false
option.PROCEDURAL_STARS=true false

# Multi-choice
option.WAVETYPE=0 1
option.FOGTYPE=0 1 2

# Slider UI
sliders = BLOOM_THRESHOLD BLOOM_STRENGTH BLOOM_RADIUS GRAIN_STRENGTH

# ===== LIGHTING =====
screen.LIGHTING = [TERRAIN] [SKY] [WATER] [ATMOS]

screen.TERRAIN = HALF_LAMBERT CLOUD_SHADOWS SUN_SSS
screen.SKY = PROCEDURAL_STARS
screen.WATER=WAVETYPE
value.WAVETYPE.0=Simple
value.WAVETYPE.1=Detailed
screen.ATMOS=FOGTYPE
value.FOGTYPE.0=Disabled
value.FOGTYPE.1=Linear
value.FOGTYPE.1=Volumetric

# ===== POST PROCESS =====
screen.POST_PROCESS = [BLOOMS] [TEXTURES] [PROCEDURAL]

screen.BLOOMS = BLOOM BLOOM_THRESHOLD BLOOM_STRENGTH BLOOM_RADIUS
screen.TEXTURES = [GRAIN] DITHERING
screen.GRAIN = GRAIN_STRENGTH
screen.PROCEDURAL = SUNGLOW